# Generated by Django 4.2.6 on 2023-11-26 22:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category_rename_status_name_status_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 27, 1, 25, 45, 95124), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 27, 1, 25, 45, 96123), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 27, 1, 25, 45, 97109), verbose_name='Дата заказа'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image', models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к картинке')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Список товаров',
                'db_table': 'Products',
            },
        ),
    ]
